# docs: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/workflows
      - /.github/actions/* # Not working until resolved: https://github.com/dependabot/dependabot-core/issues/6345
      - /.github/actions/setup
    target-branch: beta
    schedule:
      interval: monthly
      timezone: America/Detroit
      time: '06:00'
    groups:
      github_actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    target-branch: beta
    schedule:
      interval: weekly
      day: sunday
      timezone: America/Detroit
      time: '06:00'
    commit-message:
      prefix: 'chore(deps)'
    labels:
      - dependencies
    groups:
      production-deps:
        dependency-type: production
        update-types:
          - minor
          - patch
        patterns:
          - '*'
        exclude-patterns:
          - 'drizzle*'
      dev-deps:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - '*'
        exclude-patterns:
          - 'drizzle*'

  # Only bump patch versions for 2.x
  - package-ecosystem: npm
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: sunday
      timezone: America/Detroit
      time: '06:00'
    commit-message:
      prefix: 'chore(deps)'
    labels:
      - dependencies
    groups:
      production-deps:
        dependency-type: production
        update-types:
          - patch
        patterns:
          - '*'
        exclude-patterns:
          - 'drizzle*'
