name: lock-issues

on:
  schedule:
    # Run nightly at 12am EST
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  issues: write

jobs:
  lock_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Lock issues
        uses: dessant/lock-threads@v5
        with:
          process-only: 'issues'
          issue-inactive-days: '1'
          log-output: true
          issue-comment: >
            This issue has been automatically locked.

            Please open a new issue if this issue persists with any additional detail.
