name: post-release

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to process (optional)'
        required: false
        default: ''

env:
  DO_NOT_TRACK: 1 # Disable Turbopack telemetry
  NEXT_TELEMETRY_DISABLED: 1 # Disable Next telemetry
  PAYLOAD_RELEASE_EVENT: payload-release-event

jobs:
  post_release:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-24.04
    if: ${{ github.event_name != 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/release-commenter
        continue-on-error: true
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag-filter: 'v\d'

          # Change to blank to disable commenting
          # comment-template: ''

          comment-template: |
            ðŸš€ This is included in version {release_link}

  github-releases-to-discord:
    runs-on: ubuntu-24.04
    if: ${{ github.event_name != 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.19.0
        with:
          webhook_url: ${{ secrets.DISCORD_RELEASES_WEBHOOK_URL }}
          color: '16777215'
          username: 'Payload Releases'
          avatar_url: 'https://l4wlsi8vxy8hre4v.public.blob.vercel-storage.com/discord-bot-logo.png'
